//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusManagement.Pages
{


	 public partial class WebForm1
	 {

		  /// <summary>
		  /// form1 control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.HtmlControls.HtmlForm form1;

		  /// <summary>
		  /// GridView1 control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.GridView GridView1;

		  /// <summary>
		  /// BusList control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList BusList;

		  /// <summary>
		  /// BienSoXe control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox BienSoXe;

		  /// <summary>
		  /// SoXe control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox SoXe;

		  /// <summary>
		  /// SoChoNgoi control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox SoChoNgoi;

		  /// <summary>
		  /// TrangThai control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.TextBox TrangThai;

		  /// <summary>
		  /// bustypelist control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList bustypelist;

		  /// <summary>
		  /// tuyenlist control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.DropDownList tuyenlist;

		  /// <summary>
		  /// AddBusButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button AddBusButton;

		  /// <summary>
		  /// UpdateBusButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button UpdateBusButton;

		  /// <summary>
		  /// DeleteBusButton control.
		  /// </summary>
		  /// <remarks>
		  /// Auto-generated field.
		  /// To modify move field declaration from designer file to code-behind file.
		  /// </remarks>
		  protected global::System.Web.UI.WebControls.Button DeleteBusButton;
	 }
}
